[package]
name        = "sv-crypto"
version.workspace     = true
edition.workspace     = true
rust-version.workspace= true
license.workspace     = true
repository.workspace  = true
description = "Sovereign Vault cryptographic primitives: AEAD, KDF, key wrap, zeroization."

[dependencies]
thiserror         = { workspace = true }
zeroize           = { workspace = true }
sha2              = { workspace = true }
hkdf              = { workspace = true }
chacha20poly1305  = "0.10"
argon2            = "0.5"
rand              = "0.9"
getrandom         = "0.2"
ed25519-dalek     = { workspace = true }

[lints]
workspace = true
