<script lang="ts">
  import { X } from 'lucide-svelte';
  import type { ApprovalPrompt } from '../lib/types';
  import { approvalStore } from '../stores/approvals.svelte';
  import { toastStore } from '../stores/toast.svelte';

  let { prompt, onClose }: { prompt: ApprovalPrompt; onClose: () => void } = $props();

  let otpInput = $state('');

  async function submit() {
    if (!otpInput.trim()) { toastStore.setError('Enter the OTP code.'); return; }
    try {
      await approvalStore.respond(prompt.id, true, otpInput.trim());
      onClose();
    } catch (e) {
      toastStore.setError(e);
    }
  }
</script>

<div class="modal-shell" role="dialog" aria-modal="true">
  <div class="modal-card panel-card" style="max-width:400px;width:100%">
    <div class="panel-header">
      <div>
        <p class="eyebrow">OTP container</p>
        <h3>One-time password required</h3>
      </div>
      <button class="ghost-button" onclick={onClose}><X size={16} /></button>
    </div>

    {#if prompt.otp_code}
      <div class="notice-banner" style="font-family:var(--font-mono);font-size:1.4rem;letter-spacing:0.2em;text-align:center">
        {prompt.otp_code}
      </div>
      <p style="color:var(--muted);font-size:0.85rem;margin-top:0.75rem">
        This code was generated by the vault. Share it with the MCP caller.
      </p>
    {:else}
      <label class="field">
        <span>OTP code</span>
        <input type="text" placeholder="123456" bind:value={otpInput} />
      </label>
      <div style="display:flex;gap:0.75rem;margin-top:1rem;justify-content:flex-end">
        <button class="ghost-button" onclick={async () => {
          try { await approvalStore.respond(prompt.id, false); } catch (e) { toastStore.setError(e); }
          onClose();
        }}>Cancel</button>
        <button class="primary-button" onclick={submit}>Submit</button>
      </div>
    {/if}
  </div>
</div>
