[package]
name        = "sovereign-vault"
version.workspace     = true
edition.workspace     = true
rust-version.workspace= true
license.workspace     = true
repository.workspace  = true
description = "Sovereign Vault headless CLI."

[[bin]]
name = "sovereign-vault"
path = "src/main.rs"

[dependencies]
sv-core = { workspace = true }
